### ISSUE TITLE
RaspPi interaction

### ISSUE THREAD

**Issue by robertofiguz** [mik4el/gadget-circadian-hallway#1]
How does the Arduino code interact with the raspberry pi?

**Comment by mik4el** [comment]
The Arduino is connected with usb to the raspi, then on the raspi this python script: https://github.com/mik4el/circadian_hallway/blob/master/send_serial_command.py switches between the different modes. The python script is run either manually or once every day by e.g. crontab to set your different modes.

I hope the code can be useful to you! It has been running now for a long time without problems.
